"""add author surname

Revision ID: 82641097c6de
Revises: b8acfb504450
Create Date: 2022-12-01 21:02:13.573735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82641097c6de'
down_revision = 'b8acfb504450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
